'use strict';
const { contextBridge, ipcRenderer, webFrame, webUtils } = require('electron');

contextBridge.exposeInMainWorld('sms', {
  state: () => ipcRenderer.invoke('state'),
  copyActivityLog: () => ipcRenderer.invoke('copy-activity-log'),
  saveActivityLog: () => ipcRenderer.invoke('save-activity-log'),
  checkTools: () => ipcRenderer.invoke('check-tools'),
  copyMacCommand: index => ipcRenderer.invoke('copy-mac-command', index),
  saveSettings: value => ipcRenderer.invoke('save-settings', value),
  savePrompts: images => ipcRenderer.invoke('save-prompts', images),
  displayInfo: () => ipcRenderer.invoke('display-info'),
  openHdrCalibration: () => ipcRenderer.invoke('open-hdr-calibration'),
  chooseRom: () => ipcRenderer.invoke('choose-rom'),
  chooseRepo: () => ipcRenderer.invoke('choose-repo'),
  chooseLocation: () => ipcRenderer.invoke('choose-location'),
  installPort: () => ipcRenderer.invoke('install-port'),
  updatePort: () => ipcRenderer.invoke('update-port'),
  setGameSource: value => ipcRenderer.invoke('set-game-source', value),
  installEclipse: () => ipcRenderer.invoke('install-eclipse'),
  installTextures: () => ipcRenderer.invoke('install-textures'),
  build: () => ipcRenderer.invoke('build'),
  setupGame: () => ipcRenderer.invoke('setup-game'),
  play: () => ipcRenderer.invoke('play'),
  playPrevious: () => ipcRenderer.invoke('play-previous'),
  launchGame: () => ipcRenderer.invoke('launch-game'),
  cleanPreview: () => ipcRenderer.invoke('clean-preview'),
  clean: () => ipcRenderer.invoke('clean'),
  backupSaves: () => ipcRenderer.invoke('backup-saves'),
  steamStatus: () => ipcRenderer.invoke('steam-status'),
  addToSteam: options => ipcRenderer.invoke('add-to-steam', options),
  importDolphinSave: file => {
    const filePath = file ? webUtils.getPathForFile(file) : null;
    if (file && !filePath) throw new Error('Drop a .gci file from your computer.');
    return ipcRenderer.invoke('import-dolphin-save', filePath);
  },
  restoreSaves: id => ipcRenderer.invoke('restore-saves', id),
  openBackups: () => ipcRenderer.invoke('open-backups'),
  stop: () => ipcRenderer.invoke('stop'),
  openDocs: () => ipcRenderer.invoke('open-docs'),
  openDiscord: () => ipcRenderer.invoke('open-discord'),
  changelog: () => ipcRenderer.invoke('changelog'),
  markChangelogSeen: () => ipcRenderer.invoke('changelog-seen'),
  openChangelogPage: () => ipcRenderer.invoke('open-changelog-page'),
  checkAppUpdate: () => ipcRenderer.invoke('check-app-update'),
  installAppUpdate: () => ipcRenderer.invoke('install-app-update'),
  updateChannels: () => ipcRenderer.invoke('update-channels'),
  zoomFactor: () => webFrame.getZoomFactor(),
  windowState: () => ipcRenderer.invoke('window-state'),
  minimizeWindow: () => ipcRenderer.invoke('window-minimize'),
  toggleFullScreen: () => ipcRenderer.invoke('window-toggle-full-screen'),
  closeWindow: () => ipcRenderer.invoke('window-close'),
  onWindowState: callback => ipcRenderer.on('window-state', (_event, value) => callback(value)),
  onLog: callback => ipcRenderer.on('log', (_event, line) => callback(line)),
  onLogReset: callback => ipcRenderer.on('log-reset', (_event, sequence) => callback(sequence)),
  onActivity: callback => ipcRenderer.on('activity', (_event, value) => callback(value)),
  onAppUpdate: callback => ipcRenderer.on('app-update', (_event, value) => callback(value)),
  onOnline: callback => ipcRenderer.on('online', (_event, value) => callback(value))
});
