'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('sms', {
  state: () => ipcRenderer.invoke('state'),
  checkTools: () => ipcRenderer.invoke('check-tools'),
  copyMacCommand: index => ipcRenderer.invoke('copy-mac-command', index),
  saveSettings: value => ipcRenderer.invoke('save-settings', value),
  chooseRom: () => ipcRenderer.invoke('choose-rom'),
  chooseRepo: () => ipcRenderer.invoke('choose-repo'),
  chooseLocation: () => ipcRenderer.invoke('choose-location'),
  installPort: () => ipcRenderer.invoke('install-port'),
  updatePort: () => ipcRenderer.invoke('update-port'),
  setGameSource: value => ipcRenderer.invoke('set-game-source', value),
  installEclipse: () => ipcRenderer.invoke('install-eclipse'),
  installTextures: () => ipcRenderer.invoke('install-textures'),
  build: () => ipcRenderer.invoke('build'),
  setupGame: () => ipcRenderer.invoke('setup-game'),
  play: () => ipcRenderer.invoke('play'),
  playPrevious: () => ipcRenderer.invoke('play-previous'),
  launchGame: () => ipcRenderer.invoke('launch-game'),
  cleanPreview: () => ipcRenderer.invoke('clean-preview'),
  clean: () => ipcRenderer.invoke('clean'),
  backupSaves: () => ipcRenderer.invoke('backup-saves'),
  restoreSaves: id => ipcRenderer.invoke('restore-saves', id),
  openBackups: () => ipcRenderer.invoke('open-backups'),
  stop: () => ipcRenderer.invoke('stop'),
  openDocs: () => ipcRenderer.invoke('open-docs'),
  checkAppUpdate: () => ipcRenderer.invoke('check-app-update'),
  installAppUpdate: () => ipcRenderer.invoke('install-app-update'),
  updateChannels: () => ipcRenderer.invoke('update-channels'),
  windowState: () => ipcRenderer.invoke('window-state'),
  minimizeWindow: () => ipcRenderer.invoke('window-minimize'),
  toggleFullScreen: () => ipcRenderer.invoke('window-toggle-full-screen'),
  closeWindow: () => ipcRenderer.invoke('window-close'),
  onWindowState: callback => ipcRenderer.on('window-state', (_event, value) => callback(value)),
  onLog: callback => ipcRenderer.on('log', (_event, line) => callback(line)),
  onActivity: callback => ipcRenderer.on('activity', (_event, value) => callback(value)),
  onAppUpdate: callback => ipcRenderer.on('app-update', (_event, value) => callback(value))
});
